# Generated by Django 2.0.4 on 2018-04-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='attended_or_not',
            field=models.CharField(default='NO', max_length=20),
        ),
    ]
